# configs/configs.yaml
seed: 22
device: cuda
cudnn_deterministic: true
cudnn_benchmark: false
checkpoints: '/home/jiangchengxuan/PycharmProjects/RL-Autovehicles-gymnasium/checkpoints'
log_path: '/home/jiangchengxuan/PycharmProjects/RL-Autovehicles-gymnasium/logs'

model:
  name: "MlpNet"
  model_args:
    num_classes: 10
    in_channels: 1

train:
  batch_size: 1024
  buffer_size: 500000
  epochs: 1000
  max_step: 1000
  min_start_train: 10  # 最小训练启动样本量