# configs/configs.yaml
seed: 22
device: cuda
cudnn_deterministic: true
cudnn_benchmark: false
checkpoints: '/checkpoints'
log_path: '/logs'

model:
  name: "MlpNet"
  model_args:
    num_classes: 10
    in_channels: 1

train:
  batch_size: 64
  buffer_size: 500000
  epochs: 1000
  max_step: 1024
  start_count: 1  # 开始训练时候缓冲区轨迹数量
  amplifier_c: 1.1
  amplifier_m: 10 # 10回合更新一次m