# configs/configs.yaml
seed: 22
device: cuda
cudnn_deterministic: true
cudnn_benchmark: false
checkpoints: '/checkpoints'
log_path: '/logs'

model:
  name: "MlpNet"
  model_args:
    num_classes: 10
    in_channels: 1

train:
  batch_size: 64
  buffer_size: 500000
  epochs: 1000
  max_step: 128
  min_start_train: 1  # 最小训练启动样本量
  actor_interval: 10