{
        "action": {
            "type": "ContinuousAction", # 线性动作
            "acceleration_range": [0, 1.0],       # 纵向加速度范围 (m/s²)
            "steering_range": [-0.785, 0.785],     # 转向角范围 (弧度，约 ±45°)
            "speed_range":[18.0,20.0],       # 可达速度范围 [m/s]
            "longitudinal": True,       # 启用油门控制
            "lateral": True,        # 启用转向控制
            "dynamical": False,      # 是否模拟动力学（例如摩擦力）而非运动学
        },
        "vehicles_density":3.0,
        "lanes_count": 4,   # 车道数
        "vehicles_count": 50,   # 车辆数
        "duration": 200,  # [s]  # 时间s
        "initial_spacing": 1.0,   # 初始间距
        "collision_reward": -1000,  # 碰撞奖励
        "reward_speed_range": [10, 20],  # [m/s] 从这个范围到最高速度的奖励呈线性关系 [0, HighwayEnv.HIGH_SPEED_REWARD].
        "simulation_frequency": 15,  # [Hz] 模拟频率
        "policy_frequency": 5,  # [Hz]  策略频率
        "other_vehicles_type": "highway_env.vehicle.behavior.AggressiveVehicle",   # 其他车辆类型:IDMVehicle(策略性变道超车)，LinearVehicle(线性速度)，AggressiveVehicle（侵略性驾驶），DefensiveVehicle（防御性驾驶）
        "screen_width": 600,  # [px]  # 显示宽度
        "screen_height": 150,  # [px] # 显示高度
        "centering_position": [0.3, 0.5],   # 居中位置
        "scaling": 5.5,   # 缩放
        "show_trajectories": False,   # 显示轨迹
        "render_agent": True,   # 渲染智能体
        "offscreen_rendering": False    # 屏幕外渲染
}